services:
  api:
    build: .
    container_name: sms_api
    ports:
      - "2020:2020"
      - "4040:4040"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    restart: always
    user: root
